WebApplication4/Controllers/ParkingController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class ParkingController : Controller
    {
        private string connStr = "";

        

        // GET: Parking/Create
        public ActionResult Create()
        {
            Parking p = new Parking();
          
            return View("AddParking", p);
        }

        // POST: Parking/Create
        [HttpPost]
        [Authorize(Roles ="admin")]
        public ActionResult Create(Parking p)
        {
            connStr = ConfigurationManager.ConnectionStrings["ParkingManagementConnection"].ConnectionString;
            if (ModelState.IsValid)
            {
                ParkingManagement pdb = new ParkingManagement();
               
                try
                {
                    if (pdb.addParkingInDB(p, connStr)>0)
                    {
                        TempData["Success"] = "Parking have been added Successfully!";

                    }
                    return Create();
                }
                catch(Exception ex)
                {
                    ViewBag.errorMessage = "could not add parking in the system due to" + ex.Message+" Try Again!";
                    return Create();
                }
            }
            return Create();


        }

        // GET: Parking/Edit/5 get the View of Parking menu 
        public ActionResult Show()
        {
            connStr = ConfigurationManager.ConnectionStrings["ParkingManagementConnection"].ConnectionString;
            ShowParking showP = new ShowParking();
            try
            {
                ParkingManagement p = new ParkingManagement();
                p.updateExpiredParkingByDate(connStr);
                return View("ShowParkings", showP);
            }
            catch(Exception ex) 
            {
                ViewBag.errorMessage = "Could Not Update Expired Parking "+ex.Message;
                return View("ShowParkings", showP);
            }
        }

        // POST: Parking/Edit/5 get the ParkingList based on the selection from the parking menu
        [HttpPost]
        public ActionResult ShowController( ShowParking sp)
        {
            connStr = ConfigurationManager.ConnectionStrings["ParkingManagementConnection"].ConnectionString;
            try
            {
                ParkingManagement pm = new ParkingManagement();
                 List<Parking> parkingList=pm.getParkingList(connStr,sp);
                List<ShowParking> ListOfReservation = pm.getParkingFromReservation(connStr,sp);                     

                List<string> reservedId= getReservedList(sp,ListOfReservation);

                int price=getPricePerHour(sp);
                for (int i=0; i<parkingList.Count; i++)
                {
                    for (int j = 0; j < reservedId.Count; j++)
                    {
                        if (parkingList[i].ParkingNumber == reservedId[j])
                        {
                            parkingList[i].ParkingNumber=null;
                        }
                        
                    }
                    parkingList[i].Price = price;
                }
               
                sp.ParkingList = parkingList;
                sp.ListOfAsiel=pm.getNumberOfAsiel(connStr,sp.Selectedbuilding,sp.Selectedlevel);
                 sp.ListOfAsiel.Sort();
                Session["parkings"] = parkingList;
                return View("ShowParkings",sp);
            }
            catch(Exception ex)
            {
                ViewBag.errorMessage = "Error occur while fetching parking from DataBase"+ex.Message;
                return View("ShowParkings",sp);
            }
        }
        
       public  List<string> getReservedList(ShowParking sp,List<ShowParking> lsp)
        {
            List<string> listOFID = new List<string>();
            for (int i=0; i<lsp.Count; i++)
            {

                if (sp.DateIn > lsp[i].DateOut & sp.DateIn<lsp[i].DateIn)
                {
                    listOFID.Add(lsp[i].ParkingID);
                    
                }
                else if (sp.DateIn == lsp[i].DateIn)
                {
                    listOFID.Add(lsp[i].ParkingID);
                }
                else if(sp.DateOut>lsp[i].DateIn & sp.DateOut < lsp[i].DateOut)
                {
                    listOFID.Add(lsp[i].ParkingID);

                }

            }
            return listOFID;

        }
        public int getPricePerHour(ShowParking sp)
        { int price = 0;
            var timeStart=sp.TimeIn.ToString("HH:mm");
            DateTime st = Convert.ToDateTime(timeStart);

            DateTime startDt = new DateTime(sp.DateIn.Date.Year,sp.DateIn.Date.Month,sp.DateIn.Date.Day,st.Hour,st.Minute,st.Second);

            var timeEnd = sp.TimeOut.ToString("HH:mm");
            DateTime et = Convert.ToDateTime(timeEnd);
            DateTime endtDt = new DateTime(sp.DateOut.Date.Year, sp.DateOut.Date.Month, sp.DateOut.Date.Day, et.Hour, et.Minute, et.Second);
            TimeSpan span =endtDt.Subtract(startDt);
            var hours = span.Hours;
            var days = span.Days;
             
            if (hours  <=2  && days==0)
            {
                price=2;
            }
            else if(days>0 )
            {
                price = hours+(days*24);
            }
            else
            {
                price = hours;
            }
            return price;


        }
        // reserve the selected parking 
        [HttpPost]
        public ActionResult ReserveParking(ShowParking sp,string parkingIdButton,List<Parking> parking)
        {
            
            sp.ParkingID=parkingIdButton;
            sp.ParkingList = (List<Parking>)Session["parkings"];
            //get the selected Parking from Parking List 
          if(sp.ParkingList!=null)
            {
                for (int i=0; i<sp.ParkingList.Count; i++)
                {
                    if (sp.ParkingList[i].ParkingNumber == sp.ParkingID)
                    {
                        sp.Asiel = sp.ParkingList[i].Asiel;
                        sp.Price = sp.ParkingList[i].Price;
                    }
                }
            }
            Session["parkings"] = null;        
            return RedirectToAction("ReserveParking", "Reservation", new RouteValueDictionary(sp));
        }
        // GET: Parking/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Parking/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication4/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomeView</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index","Home")">Reserve Parking</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                
                <div class="collapse navbar-collapse" id="navbar-collapse">
                    <ul  class="nav navbar-nav navbar-right">
                        @if (HttpContext.Current.Request.IsAuthenticated == false)
                        {
                            <li><a id="signIn" href="@Url.Action("LogIn", "Account")">Log In</a></li>
                            <li><a id="signup" href="@Url.Action("Create", "Account")">sign Up</a></li>
                        }else    
                        {
                            <li><a href="#"> @HttpContext.Current.User.Identity.Name</a></li>
                            <li><a id="Log Out" href="@Url.Action("LogOut", "Account")">Log Out</a></li>

                        }

                        <li><form class="navbar-form navbar-right">
                     <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                        </form></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <nav class="navbar navbar-default ">
            <div class="container-fluid">
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target="#navbar-collapse1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>

                    </button>
                </div>
                </div>
            <div class="collapse navbar-collapse" id="#navbar-collapse1">
                <ul class="nav nav-tabs">
                    <li><a class="active" href="@Url.Action("Show","Parking")">Find Parking</a></li>
                    <li><a class="active" href="@Url.Action("ReserveView","Reservation")">Reserve</a></li>
                    @if(ViewContext.HttpContext.User.IsInRole("admin"))
                    {
                        <li><a href="@Url.Action("Create","Parking")">Add Parking</a></li>
                        <li><a href="#">Delete parking </a></li>
                        <li><a href="#">Edit Parking</a></li>
                    }
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Help</a></li>
                    </ul>
                </div>
            </nav>
    </header>

    @RenderBody()

    <footer></footer>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript"  src="~/Scripts/jquery.validate.js"></script>
    <script type="text/javascript"  src="~/Scripts/jquery.validate.unobtrusive.js"></script> 
</body>
</html>